"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { FieldShell, controlClassName } from "@/components/ui/field";
import { changeStudentPasswordAction } from "@/lib/student/profile-actions";
export function PasswordForm() { const router = useRouter(); const [form, setForm] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" }); const [errors, setErrors] = useState<Record<string, string>>({}); const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null); const [pending, startTransition] = useTransition(); return <div className="mx-auto max-w-xl space-y-5"><header className="student-page-header"><h1 className="text-2xl font-bold text-slate-900">Change password</h1><p className="mt-1 text-sm text-slate-600">Use at least 8 characters with uppercase, lowercase and a number.</p></header><Card><CardContent className="space-y-4 p-6">{message ? <p className={`rounded-lg p-3 text-sm ${message.ok ? "bg-amber-50 text-amber-800" : "bg-red-50 text-red-700"}`}>{message.text}</p> : null}{(["currentPassword", "newPassword", "confirmPassword"] as const).map((key) => <FieldShell key={key} id={key} label={({ currentPassword: "Current password", newPassword: "New password", confirmPassword: "Confirm new password" })[key]} error={errors[key]}><input id={key} type="password" value={form[key]} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} className={controlClassName(Boolean(errors[key]), "h-10")} autoComplete={key === "currentPassword" ? "current-password" : "new-password"} /></FieldShell>)}<div className="flex gap-3"><Button isLoading={pending} onClick={() => startTransition(async () => { const result = await changeStudentPasswordAction(form); setErrors(result.fieldErrors ?? {}); setMessage({ ok: result.ok, text: result.message ?? result.error ?? "Unable to change password." }); if (result.ok) setTimeout(() => router.push("/login"), 900); })}>Change password</Button><Link href="/student/profile" className="inline-flex h-10 items-center rounded-lg border border-slate-300 px-4 text-sm font-medium">Cancel</Link></div></CardContent></Card></div>; }
